# Generated by Django 3.1.7 on 2021-07-27 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=150)),
                ('short_url', models.CharField(max_length=20, unique=True)),
                ('total_clicks', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ip_address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('ip', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Link_only_ip_address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('ip', models.CharField(max_length=50)),
                ('device', models.CharField(default='None', max_length=100)),
                ('country', models.CharField(default='None', max_length=50)),
                ('click', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('cou', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.countries')),
                ('dev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.devices')),
                ('i_p', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ip_address')),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
