# Generated by Django 3.1.7 on 2021-07-29 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link_only_ip_address',
            name='cou',
        ),
        migrations.RemoveField(
            model_name='link_only_ip_address',
            name='dev',
        ),
        migrations.RemoveField(
            model_name='link_only_ip_address',
            name='i_p',
        ),
    ]
