# Generated by Django 3.1.7 on 2021-08-15 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210729_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='titles',
            field=models.CharField(blank=True, default='No title found', max_length=200, null=True),
        ),
    ]
