# Generated by Django 3.1.7 on 2021-04-25 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210425_0409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='short_url',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
