# Generated by Django 3.1.7 on 2021-05-11 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210425_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
