# Generated by Django 3.1.7 on 2021-08-28 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_customer_titles'),
    ]

    operations = [
        migrations.AddField(
            model_name='link_only_ip_address',
            name='qr_code',
            field=models.ImageField(default='../static/young-man-avatar.jpg', upload_to='QR_codes'),
        ),
    ]
