# Generated by Django 3.1.7 on 2021-08-28 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_link_only_ip_address_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link_only_ip_address',
            name='qr_code',
            field=models.ImageField(default='../static/images/young-man-avatar.jpg', upload_to='QR_codes'),
        ),
    ]
