# Generated by Django 3.1.7 on 2021-08-28 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210828_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link_only_ip_address',
            name='qr_code',
        ),
    ]
