# Generated by Django 3.1.7 on 2021-07-05 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210705_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ip_address',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
