# Generated by Django 3.1.7 on 2021-07-07 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_link_only_ip_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link_only_ip_address',
            options={'ordering': ['date']},
        ),
        migrations.AddField(
            model_name='link_only_ip_address',
            name='device',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
