# Generated by Django 3.1.7 on 2021-08-28 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_link_only_ip_address_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link_only_ip_address',
            name='qr_code',
        ),
        migrations.AddField(
            model_name='customer',
            name='qr_code',
            field=models.ImageField(default='../static/images/young-man-avatar.jpg', upload_to='QR_codes'),
        ),
    ]
