# Generated by Django 3.1.7 on 2021-07-07 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_link_only_ip_address_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link_only_ip_address',
            name='country',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
