# Generated by Django 3.1.7 on 2021-07-24 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210707_1512'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ip_address',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='link_only_ip_address',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='link_only_ip_address',
            name='click',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
