# Generated by Django 3.1.7 on 2021-07-26 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210724_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
