# Generated by Django 3.1.7 on 2021-07-26 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_customer_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='coun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numb', models.IntegerField(blank=True, null=True)),
                ('L_ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.link_only_ip_address')),
            ],
        ),
    ]
